version: '3.8'

services:
  server:
    env_file:
      "./server/.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "devsfood-backend"
    ports:
      - "5000:5000"
    depends_on:
      - postgresqls
    volumes:
      - ./server:/home/node/app

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "devsfood-frontend"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - '.:/app'
      - '/app/node_modules'

  postgresqls:
    container_name: "postgresqlpostgis"
    image: "postgis/postgis"
    ports: 
      - "5432:5432"
    volumes:
       - db_persdata:/var/lib/postgrespers
    env_file:
      "./server/.env"
    networks:
      - default
networks:
  default:
volumes:
  db_persdata : {}